ci:
    autoupdate_schedule: quarterly


# https://pre-commit.com/
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: debug-statements
      - id: mixed-line-ending
    # This wants to go before isort & flake8
  - repo: https://github.com/PyCQA/autoflake
    rev: "v2.2.1"
    hooks:
      - id: autoflake # isort should run before black as black sometimes tweaks the isort output
        args: ["--in-place", "--ignore-init-module-imports"]
  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: ["--profile", "black"]
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.13.0
    hooks:
      - id: pyupgrade
        args:
          - "--py38-plus"
  # https://github.com/python/black#version-control-integration
  - repo: https://github.com/psf/black
    rev: 23.9.1
    hooks:
      - id: black
      - id: black-jupyter
  - repo: https://github.com/keewis/blackdoc
    rev: v0.3.8
    hooks:
      - id: blackdoc
        exclude: docs/index.rst
  - repo: https://github.com/PyCQA/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.5.1
    hooks:
      - id: mypy
        exclude: "properties|asv_bench"
        # This is slow and so we take it out of the fast-path; requires passing
        # `--hook-stage manual` to pre-commit
        stages: [manual]
        additional_dependencies: [
            # Type stubs
            types-python-dateutil,
            types-pkg_resources,
            types-PyYAML,
            types-pytz,
            typing-extensions,
            numpy,
          ]
