version: 2

build:
  os: ubuntu-20.04
  tools:
    python: "mambaforge-4.10"
  jobs:
    post_install:
    - python -m pip install -e .
    - python -c "import xbitinfo as xb; xb.install()"
    - julia -e "using Pkg; Pkg.status()"
    - julia -e "using Pkg; Pkg.add(BitInformation)"
    - python -c "import xbitinfo as xb; xb.install()"
    - julia -e "using Pkg; Pkg.status()"
    - conda env list
    - conda list
    - which python
    - which conda
    - mamba install xbitinfo -y
    - python -m pip install -e .
    - python -c "import xbitinfo as xb; xb.install()"
    - julia -e "using Pkg; Pkg.status()"
    - python -c "import julia; julia.install(); import xbitinfo as xb; xb.install()"


conda:
  environment: docs/environment.yml

sphinx:
  fail_on_warning: false

formats: []
