version: 2

build:
  os: ubuntu-20.04
  tools:
    python: "mambaforge-4.10"
  commands:
    - mamba install docs/environment.yml
    - conda env list
    - conda list
    - which python
    - which conda
    - mamba install xbitinfo -y
    - python -m pip install -e .
    - python -c "import xbitinfo as xb; xb.install()"
    - julia -e "using Pkg; Pkg.status()"
    - python -c "import xbitinfo as xb"

sphinx:
  fail_on_warning: false

formats: []
