version: 2

build:
  os: ubuntu-20.04
  tools:
    python: "mambaforge-4.10"
  commands:
    - mamba env create docs/environment.yml -n docs
    - conda activate docs
    - conda env list
    - conda list
    - which python
    - which conda
    - julia -e "using Pkg; Pkg.status()"
    - python -c "import xbitinfo as xb"

sphinx:
  fail_on_warning: false

formats: []
