version: 2

build:
  os: ubuntu-20.04
  tools:
    python: "mambaforge-4.10"
  jobs:
    post_install:
    - conda list
    - which python
    - mamba env update docs/environment.yml --name 150
    - which python
    - mamba install "sphinx-book-theme>=0.1.7"
    - conda info
    - conda env list
    - conda list
    - which conda
    - pip install readthedocs-sphinx-ext
    - conda list
    - julia -e "using Pkg; Pkg.status()"
    - python -c "import xbitinfo as xb"

conda:
  environment: docs/environment.yml

sphinx:
  fail_on_warning: false

formats: []
