version: 2

build:
  os: ubuntu-20.04
  tools:
    python: "mambaforge-4.10"
  jobs:
    post_install:
    - julia install_julia_packages.jl  # https://docs.readthedocs.io/en/stable/config-file/v2.html  # https://github.com/readthedocs/readthedocs.org/issues/1740

conda:
  environment: docs/environment.yml

sphinx:
  fail_on_warning: false

formats: []
