version: 2

build:
  os: ubuntu-20.04
  tools:
    python: "mambaforge-4.10"
  commands:
    - bash -l
    - mamba env create docs/environment.yml -n docs
    - conda init bash
    - source activate docs || true
    - which python
    - ~/.bashrc || true
    - source activate docs || true
    - which python
    - source activate /home/docs/.asdf/installs/python/mambaforge-4.10.3-10/envs/docs || true
    - which python
    - conda info
    - echo $PATH
    - export PATH=/home/docs/.asdf/installs/python/mambaforge-4.10.3-10/envs/docs/bin:$PATH
    - which python
    - conda env list
    - conda list
    - which conda
    - julia -e "using Pkg; Pkg.status()"
    - python -c "import xbitinfo as xb"

sphinx:
  fail_on_warning: false

formats: []
