name: bitinfo
channels:
  - conda-forge
dependencies:
  - python
  - julia
  - pyjulia
  - matplotlib-base
  - numpy
  - pooch
  - xarray
  - dask-core
  - jupyterlab
  - netcdf4
  - zarr
  - cfgrib
  - cdo
  - python-cdo
  - pytest
  - nb_conda_kernels
  - cmcrameri
  - asv
  - pip
  - pip:
    - git+https://github.com/observingClouds/numcodecs@bitround
    - -e .
